config/routes.rb
Rails.application.routes.draw do
  get 'pages/buy'
  get 'pages/home'
  get 'pages/about_us'
  get 'pages/prop_details'
  get 'pages/request_listing'
  root to: 'pages#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :rentals
  resources :users, except: [:new]
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :rental_categories
    has_many :rentals, through: :rental_categories
    validates :name, presence: true, uniqueness: { case_sensitive: false }, length: {minimum:3, maximum:20}
    validates_uniqueness_of :name
       
end

app/models/rental.rb
class Rental < ActiveRecord::Base
    belongs_to :user
    has_many :rentals
    has_many :rental_categories
    has_many :categories, through: :rental_categories
    validates :title, presence: true, length: {minimum:3, maximum:50}
    validates :description, presence: true, length: {minimum: 10, maximum: 10000}
    validates :user_id, presence: true
    
    def self.search_by(search_term)
        where("LOWER(title) LIKE :search_term", 
        search_term: "%#{search_term}")
    end
        
end

app/models/rental_category.rb
class RentalCategory < ActiveRecord::Base
   belongs_to :rental
   belongs_to :category    
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :rentals, dependent: :destroy
    before_save {self.email = email.downcase}
    validates :username, presence: true, 
    uniqueness: { case_sensitive: false }, 
    length: {minimum:3, maximum:25}
    
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i    
    validates :email, presence: true, uniqueness: { case_sensitive: false }, length: {maximum: 105}, format: { with: VALID_EMAIL_REGEX }

    has_secure_password
    private
        
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    helper_method :current_user, :logged_in?
    
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    def logged_in?
        !!current_user
    end
    private

    def require_user
        if !logged_in?
            flash[:danger] = "you must be logged in"
            redirect_to root_path
        end
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :require_admin_user, except: [:index, :show]
    
    def index
        @categories = Category.all
    end
    
    def show
        @category = Category.find(params[:id])
        @category_rentals = @category.rentals
    end
    
    def new
        @category = Category.new
    end

    def create
        @category = Category.new(category_params)
        if @category.save
          flash[:success] = "category successfully created"
          redirect_to @category
        else
          flash[:error] = "Something went wrong"
          render 'new'
        end
    end
    def edit
        @category = Category.find(params[:id])
    end
    def update
        @category = Category.find(params[:id])
        if @category.update_attributes(category_params)
        flash[:success] = "category name was successfully updated"
        redirect_to category_path(@category)
        else
        flash[:error] = "Something went wrong"
        render 'edit'
        end
    end
    def destroy
        @category = Category.find(params[:id])
        if @category.destroy
            flash[:success] = 'Category was successfully deleted.'
            redirect_to categories_path
        else
            flash[:error] = 'Something went wrong'
            redirect_to category_path(@category)
        end
    end
    
     
    
    private
    def category_params
        params.require(:category).permit(:name)
    end
    def require_admin_user
        if !current_user.admin?
            flash[:danger] = "only admin can add or edit categories"
            redirect_to root_path
        end
      end
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def buy
  end

  def home
  end

  def about_us
  end

  def prop_details
  end

  def request_listing
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :set_rental, only: [:edit, :update, :show, :destory]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index    
    @rentals = Rental.all
    if params[:search]
      @search_term = params[:search]
      @rentals = @rentals.search_by(@search_term)
    end
  end
  
  def new
    @rental = Rental.new
  end
  def edit
    @rental = Rental.find(params[:id])
  end
  
  def create
    @rental =Rental.new(rental_params)
    @rental.user = current_user
      if @rental.save
        flash[:success] = "We're all set, its all good"
        redirect_to rental_path(@rental)
      else
        flash[:error] = "Something went wrong"
        render 'new'
      end
  end
  def show
    @rental = Rental.find(params[:id])
  end
  def update
    @rental = Rental.find(params[:id])
    if @rental.update_attributes(rental_params)
      flash[:success] = "rental was successfully updated"
      redirect_to @rental
    else
      flash[:error] = "Something went wrong"
      render 'edit'
    end
  end
  def destroy
    @rental = Rental.find(params[:id])
    @rental.destroy
    flash[:success] = 'rental was successfully deleted.'
    redirect_to rentals_url
  end  
     
  private
  
  def rental_params
    params.require(:rental).permit(:title, :description, category_ids: [])
  end
  
  def set_rental
    @rental = Rental.find(params[:id])
  end
  def require_same_user
    if current_user != @rental.user and !current_user.admin?
        flash[:danger] = "you must be the owner of the rental"
        redirect_to root_path
    end
end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
    def create
        user = User.find_by(username: params[:session][:username])
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
           flash[:success] = "Login successfull"
           redirect_to user_path(user)
        else
            flash.now[:danger] = "There was something wrong with the login information"
            render 'new'
        end
    end
    def destroy
        session[:user_id] = nil
        flash[:success] = "logout successfull"
        redirect_to root_path
    end
    
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :show, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destory]

  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end
  def edit
    @user = User.find(params[:id])
  end
  
  def create
      @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        flash[:success] = "Welcome to the alpha rent"
        redirect_to user_path(@user)
      else
        flash[:error] = "Something went wrong"
        render 'new'
      end
  end
  def show
    @user = User.find(params[:id])
  end
  def destroy
    @user = User.find(params[:id])
    @user.destroy
      flash[:success] = 'User was successfully deleted.'
      redirect_to users_path
  end
  
  def update
    @user = User.find(params[:id])
      if @user.update_attributes(user_params)
        flash[:success] = "User was successfully updated"
        redirect_to @user
      else
        flash[:error] = "Something went wrong"
        render 'edit'
      end
  end
  
  
  private
  def user_params
      params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user and !current_user.admin?
      flash[:danger] = "you can only edit your own account"
      redirect_to root_path
    end
  end
  
  def require_admin
    if logged_in? && !current_user.admin?
      flash[:danger] = "only admins can perform that action"
      redirect_to root_path
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
 def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.username, class:"rounded-full")
 end
 
end

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category) %>

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
  <% if @category.errors.any? %>
    <h2>you encountered the following errors</h2>
    <ul>
        <% @category.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul> 
  <% end %>

<P>
    <%= f.label :name %>
    <%= f.text_field :name %>
</p>
<br>
    <%= f.submit "submit" %>
<% end %>

app/views/categories/edit.html.erb
<p>edit category name</p>
<%= render 'form' %>
          <p><%= link_to 'delete category', category_path(@category), method: :delete,data: { confirm: 'Are you sure you want to delete the category and all of their rentals?' } %></p>

app/views/categories/index.html.erb
<p class="text-blue-700 text-3xl font-bold">
all categories list
</p>
      <% if logged_in? && current_user.admin?  %>
        <%= link_to 'add categories', new_category_path, class:"block mt-4 lg:inline-block lg:mt-0 text-teal-700 font-bold hover:text-blue-700 mr-4"%>
      <% end %>
<div class="w-2/3 ml-32 bg-gray-200 border-2 border-black h-60">
  <div class="p-4">
    <% Category.all.each do |category| %>
    <div class="shadow-2xl m-3">
      <div class="p-2">
        <h4><b><%= link_to category.name, category_path(category) %></b></h4>
        <small><%= pluralize(category.rentals.count, "rentals") %></small>
        <% if logged_in? && current_user.admin? %>
          <p><%= link_to 'edit', edit_category_path(category) %></p>
          <p><%= link_to 'delete category', category_path(category), method: :delete,data: { confirm: 'Are you sure you want to delete the category and all of their rentals?' } %></p>
        <% end %>        
      </div>
    </div>      
  <% end %>
  </div>
</div>

app/views/categories/new.html.erb
<p>new category</p>
<%= render 'form' %>

app/views/categories/show.html.erb
#show
<p>
  title: <%= "Category: " + @category.name %>
</p>
 <% if logged_in? && current_user.admin? %>
          <p><%= link_to 'edit', edit_category_path(@category) %></p>
          <p><%= link_to 'delete category', category_path(@category), method: :delete,data: { confirm: 'Are you sure you want to delete the category and all of their rentals?' } %></p>
        <% end %>  
<%= render 'rentals/rental' , obj: @category_rentals%>

app/views/layouts/_nav.html.erb
<nav class="sm:hidden lg:flex bg-teal-700 items-center justify-between flex-wrap p-6">
  <div class="flex items-center flex-shrink-0 text-white mr-6">
    <svg class="fill-current h-8 w-8 mr-2" width="54" height="54" viewBox="0 0 54 54" xmlns="http://www.w3.org/2000/svg"><path d="M13.5 22.1c1.8-7.2 6.3-10.8 13.5-10.8 10.8 0 12.15 8.1 17.55 9.45 3.6.9 6.75-.45 9.45-4.05-1.8 7.2-6.3 10.8-13.5 10.8-10.8 0-12.15-8.1-17.55-9.45-3.6-.9-6.75.45-9.45 4.05zM0 38.3c1.8-7.2 6.3-10.8 13.5-10.8 10.8 0 12.15 8.1 17.55 9.45 3.6.9 6.75-.45 9.45-4.05-1.8 7.2-6.3 10.8-13.5 10.8-10.8 0-12.15-8.1-17.55-9.45-3.6-.9-6.75.45-9.45 4.05z"/></svg>
    <span class="font-semibold text-xl tracking-tight">Tailwind <%= "ADMIN Portal" if logged_in? && current_user.admin? %></span>
  </div>
  <div class="block lg:hidden">
    <button class="flex items-center px-3 py-2 border rounded text-teal-200 border-teal-400 hover:text-white hover:border-white">
      <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
    </button>
  </div>
  <div class="w-full block flex-grow lg:flex lg:items-center lg:w-auto">
    <div class="text-sm lg:flex-grow">
      <%= link_to 'rentals', rentals_path ,class:"block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4"%>
      <%= link_to 'agents', users_path ,class:"block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4"%>
      <%= link_to 'all categories', categories_path ,class:"block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4"%>
      <% if logged_in? %>
        <%= link_to 'add listing', new_rental_path, class:"block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4"%>
      <% end %>
    </div>
    
    <% if logged_in? %>
        <div>
        <%= link_to 'view profile', user_path(current_user), class: "inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-teal-500 hover:bg-white mt-4 lg:mt-0" %>
        </div>
        <div>
        <%= link_to 'edit profile', edit_user_path(current_user), class: "inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-teal-500 hover:bg-white mt-4 lg:mt-0" %>
        </div>
        <div>
        <%= link_to 'logout', logout_path, method: :delete, class: "inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-teal-500 hover:bg-white mt-4 lg:mt-0" %>
        </div>
        <% else %>
        <div>
        <%= link_to 'Log In', login_path, class: "inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-teal-500 hover:bg-white mt-4 lg:mt-0" %>
        </div>
        <div>
        <%= link_to 'Sign up', signup_path, class: "inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-teal-500 hover:bg-white mt-4 lg:mt-0" %>
        </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alpharent</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |name, msg|%>
      <ul>
        <li><%= msg %></li>
      </ul>
    <% end %>
    <%= render 'layouts/nav' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about_us.html.erb
<h1>Pages#about_us</h1>
<p>Find me in app/views/pages/about_us.html.erb</p>

app/views/pages/buy.html.erb
<h1>Pages#buy</h1>
<p>Find me in app/views/pages/buy.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/index.html.erb
<div class="bg-gray-100 mb-32">
  <div class="bg-cover bg-no-repeat h-66 bg-center"
    style="background-image: url(https://images.unsplash.com/photo-1556193151-cac363ec3657?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60)">
    <p class="text-6xl text-white font-bold text-center py-2 mb-2 capitalize pt-20">search rentals online</p>
    <div class="p-6 bg-white ml-24 mr-24 rounded shadow-2xl mt-8">
      <form>
        <div class="">
          <input
            class="bg-gray-100 py-6 px-6 m-2 border-gray-200 border-2 rounded"
            type="text" placeholder="try the nearest town">
          <input
            class="bg-gray-100 py-6 px-6 m-2 border-gray-200 border-2 rounded"
            type="text" placeholder="try any amount">
          <button
            class="bg-teal-700 py-3 px-8 text-4xl font-bold text-white"
            type="button">
            search
          </button>
        </div>
      </form>
    </div>
  </div>
</div>
<%= link_to "all categories", categories_path %>
<i class="fab fa-twitter fa-2x"></i>
<% Category.all.each do |category| %>
    <%= link_to "#{category.name}", category_path(category) %>
<% end %>

app/views/pages/request_listing.html.erb
<h1>Pages#request_listing</h1>
<p>Find me in app/views/pages/request_listing.html.erb</p>
<div class="bg-gray-400">
    <img class="object-cover h-70 object-center w-full" src="https://images.unsplash.com/photo-1564490292125-2e3c78a0ef44?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60">
  </div>
  <hr>
<div class="p-10">
    <p class="text-center text-6xl text-teal-700 font-semibold py-4 capitalize">you can reach us through: </p>
    <p class="text-left text-5xl py-4"><i class="fa fa-phone mr-4"></i>+254798767470</p>
    <p class="text-left text-5xl py-4"><i class="fa fa-envelope-open-text mr-4"></i>brianngeywo254@gmail.com</p>
</div>

app/views/rentals/_form.html.erb
<%= form_for @rental do |f| %>
  <% if @rental.errors.any? %>
    <h2>you encountered the following errors</h2>
    <ul>
        <% @rental.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul> 
  <% end %>

<P>
    <%= f.label :title %>
    <%= f.text_field :title %>
</p>
<p>
    <%= f.label :description%>
    <%= f.text_area :description %>
</p>
<br>
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
    <% cb.label(class: "text-teal-700"){cb.check_box(class: "check") + cb.text} %>
<% end %>
<br>
    <%= f.submit "submit" %>
<% end %>

app/views/rentals/_rental.html.erb
<div class="flex-none bg-gray-100">
  <div class="w-full rounded overflow-hidden shadow-lg mt-6 mb-6 bg-white p-6 pr-16 pl-16">
   <% obj.each do |rental| %>
    <img class="w-full rounded-lg h-78 object-cover object-center m-2"
      src="https://images.unsplash.com/photo-1516156008625-3a9d6067fab5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60"
      alt="Sunset in the mountains">
    <div class="px-8 py-4">
    <%= link_to rental.title, rental_path(rental), class:"font-semibold text-6xl mb-2 text-teal-700 capitalize" %>
      <div class="font-semibold text-5xl mb-2 text-gray-700 capitalize"><i
        class="fa fa-map-marker-alt mr-3"></i>eldoret , huruma</div>
       <% if rental.categories.any? %>
        <div class="font-normal text-3xl mb-2 capitalize text-gray-900"><%= render rental.categories %> &nbsp;</div>
       <% end %>
      <div class="font-normal text-4xl mb-2 capitalize text-gray-900">5,000/= per month</div>
      <div class="py-4">
        <span class="inline-block px-4 py-1 text-4xl font-bold text-gray-700 mr-5"><i
            class="fa fa-bath mr-5"></i>2</span>
        <span class="inline-block px-3 py-1 text-4xl font-semibold text-gray-700 mr-5"><i
            class="fa fa-bed mr-5"></i>3</span>
        <span class="inline-block px-3 py-1 text-4xl font-semibold text-gray-700"><i class="fa fa-car mr-5"></i>1</span>
      </div>
    </div>
   <% end %>
  </div>

  <div class="w-full rounded overflow-hidden shadow-lg mt-6 mb-6 bg-white p-6 pr-16 pl-16">
    <img class="w-full rounded-lg h-78 object-cover object-center m-2"
      src="https://images.unsplash.com/photo-1576208861541-335784ba66c9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60"
      alt="Sunset in the mountains">
    <div class="px-8 py-4">
    <%= link_to "rock gardens", pages_prop_details_path, class:"font-semibold text-6xl mb-2 text-teal-700 capitalize" %>
      <div class="font-semibold text-5xl mb-2 text-gray-700 capitalize"><i
        class="fa fa-map-marker-alt mr-3"></i>eldoret , huruma</div>
      <div class="font-normal text-4xl mb-2 capitalize text-gray-900">5,000/= per month</div>
      <div class="py-4">
        <span class="inline-block px-4 py-1 text-4xl font-bold text-gray-700 mr-5"><i
            class="fa fa-bath mr-5"></i>2</span>
        <span class="inline-block px-3 py-1 text-4xl font-semibold text-gray-700 mr-5"><i
            class="fa fa-bed mr-5"></i>3</span>
        <span class="inline-block px-3 py-1 text-4xl font-semibold text-gray-700"><i class="fa fa-car mr-5"></i>1</span>
      </div>
    </div>
  </div>

  <div class="w-full rounded overflow-hidden shadow-lg mt-6 mb-6 bg-white p-6 pr-16 pl-16">
    <img class="w-full rounded-lg h-78 object-cover object-center m-2"
      src="https://images.unsplash.com/photo-1570815086038-21b7ad0c5f1d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60"
      alt="Sunset in the mountains">
    <div class="px-8 py-4">
    <%= link_to "rock gardens", pages_prop_details_path, class:"font-semibold text-6xl mb-2 text-teal-700 capitalize" %>
      <div class="font-semibold text-5xl mb-2 text-gray-700 capitalize"><i
        class="fa fa-map-marker-alt mr-3"></i>eldoret , huruma</div>
      <div class="text-4xl mb-2 capitalize text-gray-900">5,000/= per month</div>
      <div class="py-3">
        <span class="inline-block py-1 text-4xl font-bold text-gray-700 mr-5"><i
            class="fa fa-bath mr-5"></i>2</span>
        <span class="inline-block px-3 py-1 text-4xl font-semibold text-gray-700 mr-5"><i
            class="fa fa-bed mr-5"></i>3</span>
        <span class="inline-block px-3 py-1 text-4xl font-semibold text-gray-700"><i class="fa fa-car mr-5"></i>1</span>
      </div>
    </div>
  </div>
</div>

app/views/rentals/edit.html.erb
<h1>edit rental</h1>
<%= render 'form' %>
<%= link_to 'delete listing', rental_path, method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'rentals listing', rentals_path %>

app/views/rentals/index.html.erb
<%= render 'rental' , obj: @rentals%>

app/views/rentals/new.html.erb
<h1>new rental</h1>
<%= render 'form' %>
<%= link_to 'rentals listing', rentals_path %>

app/views/rentals/show.html.erb
<% if @rental.user %>
  <p>created by:<%= link_to @rental.user.username, user_path(@rental.user) %></p>
<% end %>
<p>
  title: <%= @rental.title %>
</p>
<p>
  description: <%= simple_format(@rental.description) %>
</p>

<% if @rental.categories.any? %>
  <%= render @rental.categories %> &nbsp;
<% end %>

<% if logged_in? && (current_user == @rental.user || current_user.admin?) %>
  <p><%= link_to 'edit', edit_rental_path(@rental) %></p>
  <p><%= link_to 'delete listing', rental_path(@rental), method: :delete,data: { confirm: 'Are you sure?' } %></p>
<% end %>

  <h4><b>created by:<%= link_to @rental.user.username, user_path(@rental.user) %></b></h4>
  
        

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <h2>you encountered the following errors</h2>
    <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul> 
  <% end %>

<P>
    <%= f.label :username %>
    <%= f.text_field :username %>
</p>
<p>
    <%= f.label :email %>
    <%= f.email_field :email %>
</p>
<p>
    <%= f.label :password %>
    <%= f.password_field :password %>
</p>
<br>
    <%= f.submit (@user.new_record? ? "Create account" : "Update your account") %>
<% end %>

app/views/users/edit.html.erb
<h1>edit users</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<p class="text-blue-700 text-3xl font-bold">
all users list
</p>
<div class="w-2/3 ml-32 bg-gray-200 border-2 border-black h-60">
  <div class="p-4">
    <% @users.each do |user| %>
    <div class="shadow-2xl m-3">
      <div class="p-2">
        <p><%= link_to gravatar_for(user), user_path(user) %></p>
        <h4><b><%= link_to user.username, user_path(user) %></b></h4>
        <small><%= pluralize(user.rentals.count, "rentals") if user.rentals %></small>
        <% if logged_in? && current_user.admin? %>
          <p><%= link_to 'edit', edit_user_path(user) %></p>
          <p><%= link_to 'delete user', user_path(user), method: :delete,data: { confirm: 'Are you sure you want to delete the user and all of their rentals?' } %></p>
        <% end %>        
      </div>
    </div>      
  <% end %>
  </div>
</div>

app/views/users/new.html.erb
<h1>signup for account</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<p class="text-3xl">
  welcome to <%= @user.username %>'s page'
</p>

<div class="max-w-full rounded overflow-hidden shadow-lg">
  <%= gravatar_for @user%>
  <div class="px-6 py-4">
    <div class="font-bold text-xl mb-2"><%= @user.username %>'s rentals</div>
  </div>
  <%= render 'rentals/rental' , obj: @user.rentals%>
</div>